// <auto-generated />
using System;
using Acadify.Models.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acadify.Migrations
{
    [DbContext(typeof(AcadifyDbContext))]
    partial class AcadifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acadify.Models.Db.AcademicAdvisingConfirmationForm", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("formID");

                    b.Property<int?>("CoursesCount")
                        .HasColumnType("int")
                        .HasColumnName("coursesCount");

                    b.Property<decimal?>("CurrentGpa")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("currentGPA");

                    b.Property<string>("StudentLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("studentLevel");

                    b.Property<string>("StudentName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("studentName");

                    b.HasKey("FormId")
                        .HasName("PK__Academic__51BCB7CBD5B24476");

                    b.ToTable("AcademicAdvisingConfirmationForm", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.AcademicCalendar", b =>
                {
                    b.Property<int>("CalendarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("calendarID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalendarId"));

                    b.Property<string>("PdfFile")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pdfFile");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("uploadedAt")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("CalendarId")
                        .HasName("PK__Academic__EE5496D64E04E095");

                    b.ToTable("AcademicCalendar", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.Advisor", b =>
                {
                    b.Property<int>("AdvisorId")
                        .HasColumnType("int")
                        .HasColumnName("advisorID");

                    b.Property<string>("Department")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("department");

                    b.HasKey("AdvisorId")
                        .HasName("PK__Advisor__D0081275B285C8F3");

                    b.ToTable("Advisor", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.Community", b =>
                {
                    b.Property<int>("CommunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("communityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommunityId"));

                    b.Property<string>("CommunityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("communityName");

                    b.HasKey("CommunityId")
                        .HasName("PK__Communit__938137ADD1893FFC");

                    b.ToTable("Community", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.CommunityMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("messageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("CommunityId")
                        .HasColumnType("int")
                        .HasColumnName("communityID");

                    b.Property<DateTime?>("MessageDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("messageDate")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("messageText");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("senderName");

                    b.HasKey("MessageId")
                        .HasName("PK__Communit__4808B873AA93DB8D");

                    b.HasIndex("CommunityId");

                    b.ToTable("CommunityMessages");
                });

            modelBuilder.Entity("Acadify.Models.Db.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("courseID");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("courseName");

                    b.Property<string>("GraduationRequirement")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Hours")
                        .HasColumnType("int")
                        .HasColumnName("hours");

                    b.Property<string>("Prerequisite")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("prerequisite");

                    b.Property<string>("RequirementCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RequirementCategory");

                    b.HasKey("CourseId")
                        .HasName("PK__Course__2AA84FF1285E5A7F");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.CourseChoiceMonitoringForm", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("formID");

                    b.Property<int?>("AdvisedCreditHours")
                        .HasColumnType("int")
                        .HasColumnName("advisedCreditHours");

                    b.Property<string>("ComingSemester")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("comingSemester");

                    b.Property<string>("DropSubjects")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dropSubjects");

                    b.Property<string>("ICSubjects")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("icSubjects");

                    b.Property<string>("IpSubjects")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ipSubjects");

                    b.Property<string>("Level")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("level");

                    b.Property<int?>("RunningCreditHours")
                        .HasColumnType("int")
                        .HasColumnName("runningCreditHours");

                    b.Property<string>("SelectedCoursesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("selectedCoursesJson");

                    b.Property<string>("Semester")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("semester");

                    b.HasKey("FormId")
                        .HasName("PK_CourseChoiceMonitoringForm");

                    b.ToTable("CourseChoiceMonitoringForm", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.Form", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("formID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormId"));

                    b.Property<bool?>("AdvisorConfirmation")
                        .HasColumnType("bit");

                    b.Property<int>("AdvisorId")
                        .HasColumnType("int")
                        .HasColumnName("advisorID");

                    b.Property<string>("AdvisorNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("advisorNotes");

                    b.Property<bool>("AutoFilled")
                        .HasColumnType("bit")
                        .HasColumnName("autoFilled");

                    b.Property<DateTime>("FormDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("formDate")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("FormStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("formStatus");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("formType");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("studentID");

                    b.HasKey("FormId")
                        .HasName("PK__Forms__51BCB7CB3C44586F");

                    b.HasIndex(new[] { "AdvisorId" }, "IX_Forms_AdvisorID");

                    b.HasIndex(new[] { "StudentId" }, "IX_Forms_StudentID");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("Acadify.Models.Db.GraduationProjectEligibilityForm", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("formID");

                    b.Property<string>("Eligibility")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("eligibility");

                    b.Property<string>("RequiredCoursesStatus")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("requiredCoursesStatus");

                    b.HasKey("FormId")
                        .HasName("PK__Graduati__51BCB7CB4C7D20AB");

                    b.ToTable("GraduationProjectEligibilityForm", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.GraduationStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("statusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<int>("RemainingHours")
                        .HasColumnType("int")
                        .HasColumnName("remainingHours");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("studentID");

                    b.HasKey("StatusId")
                        .HasName("PK__Graduati__36257A384BAB0D83");

                    b.HasIndex(new[] { "StudentId" }, "UQ__Graduati__4D11D65D0913BB99")
                        .IsUnique();

                    b.HasIndex(new[] { "StudentId" }, "UQ__Graduati__4D11D65DC716F92A")
                        .IsUnique();

                    b.ToTable("GraduationStatus", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.MatchingStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("statusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("studentID");

                    b.HasKey("StatusId")
                        .HasName("PK__Matching__36257A3864A5945E");

                    b.HasIndex(new[] { "StudentId" }, "UQ__Matching__4D11D65D372F9C0A")
                        .IsUnique();

                    b.HasIndex(new[] { "StudentId" }, "UQ__Matching__4D11D65D5FAF0CEA")
                        .IsUnique();

                    b.ToTable("MatchingStatus", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.Meeting", b =>
                {
                    b.Property<int>("MeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("meetingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeetingId"));

                    b.Property<int>("AdvisorId")
                        .HasColumnType("int")
                        .HasColumnName("advisorID");

                    b.Property<string>("ChatRecord")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chatRecord");

                    b.Property<string>("ChatSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("endTime");

                    b.Property<bool>("IsRecordingStarted")
                        .HasColumnType("bit");

                    b.Property<string>("LastRecordingAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecordingStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RecordingStoppedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("startTime");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("studentID");

                    b.HasKey("MeetingId")
                        .HasName("PK__Meeting__5C5E6E64F75E2F9D");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Meeting", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.MeetingForm", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("formID");

                    b.Property<string>("AdvisorActions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("advisorActions");

                    b.Property<DateTime?>("MeetingEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("meetingEnd");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<string>("MeetingNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("meetingNotes");

                    b.Property<string>("MeetingPurpose")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("meetingPurpose");

                    b.Property<DateTime?>("MeetingStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("meetingStart");

                    b.Property<string>("ReferralReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("referralReason");

                    b.Property<string>("ReferredTo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("referredTo");

                    b.Property<string>("StudentActions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("studentActions");

                    b.HasKey("FormId")
                        .HasName("PK__MeetingF__51BCB7CBFD115046");

                    b.ToTable("MeetingForm", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.MeetingMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("messageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<bool>("IsRecorded")
                        .HasColumnType("bit");

                    b.Property<int>("MeetingId")
                        .HasColumnType("int")
                        .HasColumnName("meetingID");

                    b.Property<DateTime?>("MessageDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("messageDate")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("messageText");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("senderName");

                    b.HasKey("MessageId")
                        .HasName("PK__MeetingM__4808B873AC1C378A");

                    b.ToTable("MeetingMessages");
                });

            modelBuilder.Entity("Acadify.Models.Db.NextSemesterCourseSelectionForm", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("formID");

                    b.Property<string>("GpaChange")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gpaChange");

                    b.Property<string>("PrerequisiteViolation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("prerequisiteViolation");

                    b.Property<string>("RecommendedCourses")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("recommendedCourses");

                    b.Property<int?>("RecommendedHours")
                        .HasColumnType("int")
                        .HasColumnName("recommendedHours");

                    b.Property<string>("TrackChoice")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("trackChoice");

                    b.HasKey("FormId")
                        .HasName("PK__NextSeme__51BCB7CB0A91F16E");

                    b.ToTable("NextSemesterCourseSelectionForm", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("AdvisorId")
                        .HasColumnType("int")
                        .HasColumnName("advisorID");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("date")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("studentID");

                    b.Property<string>("Type")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("type");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__4BA5CE8975CAE89B");

                    b.HasIndex("AdvisorId");

                    b.HasIndex(new[] { "StudentId" }, "IX_Notif_StudentID");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("studentID");

                    b.Property<int?>("AdvisorId")
                        .HasColumnType("int")
                        .HasColumnName("advisorID");

                    b.Property<int?>("CohortYear")
                        .HasColumnType("int")
                        .HasColumnName("cohortYear");

                    b.Property<int>("CompletedHours")
                        .HasColumnType("int")
                        .HasColumnName("completedHours");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("level");

                    b.Property<string>("Major")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("major");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("StudentId")
                        .HasName("PK__Student__4D11D65C8C8F6A12");

                    b.HasIndex(new[] { "AdvisorId" }, "IX_Student_AdvisorID");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.StudyPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("planID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("major");

                    b.Property<string>("PdfFile")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pdfFile");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int")
                        .HasColumnName("totalHours");

                    b.HasKey("PlanId")
                        .HasName("PK__StudyPla__A2942D18973A63BF");

                    b.ToTable("StudyPlan", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.StudyPlanMatchingForm", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("formID");

                    b.Property<int?>("CollegeMandatoryHours")
                        .HasColumnType("int")
                        .HasColumnName("collegeMandatoryHours");

                    b.Property<int?>("DeptElectiveHours")
                        .HasColumnType("int")
                        .HasColumnName("deptElectiveHours");

                    b.Property<int?>("DeptMandatoryHours")
                        .HasColumnType("int")
                        .HasColumnName("deptMandatoryHours");

                    b.Property<int?>("EarnedHours")
                        .HasColumnType("int")
                        .HasColumnName("earnedHours");

                    b.Property<int?>("FreeCoursesHours")
                        .HasColumnType("int")
                        .HasColumnName("freeCoursesHours");

                    b.Property<string>("GraduationStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("graduationStatus");

                    b.Property<int?>("PrepYearHours")
                        .HasColumnType("int")
                        .HasColumnName("prepYearHours");

                    b.Property<int?>("RegisteredHours")
                        .HasColumnType("int")
                        .HasColumnName("registeredHours");

                    b.Property<int?>("RemainingHours")
                        .HasColumnType("int")
                        .HasColumnName("remainingHours");

                    b.Property<int?>("RequiredHours")
                        .HasColumnType("int")
                        .HasColumnName("requiredHours");

                    b.Property<int?>("TotalHours")
                        .HasColumnType("int")
                        .HasColumnName("totalHours");

                    b.Property<int?>("UniversityHours")
                        .HasColumnType("int")
                        .HasColumnName("universityHours");

                    b.HasKey("FormId")
                        .HasName("PK__StudyPla__51BCB7CBBA7C5B63");

                    b.ToTable("StudyPlanMatchingForm", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.Transcript", b =>
                {
                    b.Property<int>("TranscriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transcriptID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranscriptId"));

                    b.Property<string>("ExtractedCourses")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extractedCourses");

                    b.Property<string>("ExtractedInfo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extractedInfo");

                    b.Property<decimal?>("Gpa")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("GPA");

                    b.Property<string>("PdfFile")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("pdfFile");

                    b.Property<decimal?>("SemesterGpa")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("semesterGPA");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("studentID");

                    b.HasKey("TranscriptId")
                        .HasName("PK__Transcri__DF577D866E848D8C");

                    b.HasIndex(new[] { "StudentId" }, "UQ__Transcri__4D11D65D0CDDD90F")
                        .IsUnique();

                    b.HasIndex(new[] { "StudentId" }, "UQ__Transcri__4D11D65D215703ED")
                        .IsUnique();

                    b.ToTable("Transcript", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.HasKey("UserId")
                        .HasName("PK__User__CB9A1CDF81DA4C0D");

                    b.HasIndex(new[] { "Email" }, "UQ__User__AB6E6164899F0BDA")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__User__AB6E6164B149AB70")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.VwMyStudent", b =>
                {
                    b.Property<int?>("AdvisorId")
                        .HasColumnType("int")
                        .HasColumnName("advisorID");

                    b.Property<int?>("CohortYear")
                        .HasColumnType("int")
                        .HasColumnName("cohortYear");

                    b.Property<string>("GraduationStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("graduationStatus");

                    b.Property<string>("MatchingStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("matchingStatus");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("studentID");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("studentName");

                    b.ToTable((string)null);

                    b.ToView("vw_MyStudents", (string)null);
                });

            modelBuilder.Entity("StudyPlanCourse", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("planID");

                    b.Property<string>("CourseId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("courseID");

                    b.HasKey("PlanId", "CourseId")
                        .HasName("PK__StudyPla__A03EA9E70870A987");

                    b.HasIndex("CourseId");

                    b.ToTable("StudyPlanCourse", (string)null);
                });

            modelBuilder.Entity("TranscriptCourse", b =>
                {
                    b.Property<int>("TranscriptId")
                        .HasColumnType("int")
                        .HasColumnName("transcriptID");

                    b.Property<string>("CourseId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("courseID");

                    b.HasKey("TranscriptId", "CourseId")
                        .HasName("PK__Transcri__DDFDF97902CF3063");

                    b.HasIndex("CourseId");

                    b.ToTable("TranscriptCourse", (string)null);
                });

            modelBuilder.Entity("Acadify.Models.Db.AcademicAdvisingConfirmationForm", b =>
                {
                    b.HasOne("Acadify.Models.Db.Form", "Form")
                        .WithOne("AcademicAdvisingConfirmationForm")
                        .HasForeignKey("Acadify.Models.Db.AcademicAdvisingConfirmationForm", "FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AACF_Forms");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Acadify.Models.Db.Advisor", b =>
                {
                    b.HasOne("Acadify.Models.Db.User", "AdvisorNavigation")
                        .WithOne("Advisor")
                        .HasForeignKey("Acadify.Models.Db.Advisor", "AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Advisor_User");

                    b.Navigation("AdvisorNavigation");
                });

            modelBuilder.Entity("Acadify.Models.Db.CommunityMessage", b =>
                {
                    b.HasOne("Acadify.Models.Db.Community", "Community")
                        .WithMany("CommunityMessages")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CommunityMessages_Community");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Acadify.Models.Db.CourseChoiceMonitoringForm", b =>
                {
                    b.HasOne("Acadify.Models.Db.Form", "Form")
                        .WithOne("CourseChoiceMonitoringForm")
                        .HasForeignKey("Acadify.Models.Db.CourseChoiceMonitoringForm", "FormId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseChoiceMonitoringForm_Form");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Acadify.Models.Db.Form", b =>
                {
                    b.HasOne("Acadify.Models.Db.Advisor", "Advisor")
                        .WithMany("Forms")
                        .HasForeignKey("AdvisorId")
                        .IsRequired()
                        .HasConstraintName("FK_Forms_Advisor");

                    b.HasOne("Acadify.Models.Db.Student", "Student")
                        .WithMany("Forms")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Forms_Student");

                    b.Navigation("Advisor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Acadify.Models.Db.GraduationProjectEligibilityForm", b =>
                {
                    b.HasOne("Acadify.Models.Db.Form", "Form")
                        .WithOne("GraduationProjectEligibilityForm")
                        .HasForeignKey("Acadify.Models.Db.GraduationProjectEligibilityForm", "FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GPEF_Forms");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Acadify.Models.Db.GraduationStatus", b =>
                {
                    b.HasOne("Acadify.Models.Db.Student", "Student")
                        .WithOne("GraduationStatus")
                        .HasForeignKey("Acadify.Models.Db.GraduationStatus", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GradStatus_Student");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Acadify.Models.Db.MatchingStatus", b =>
                {
                    b.HasOne("Acadify.Models.Db.Student", "Student")
                        .WithOne("MatchingStatus")
                        .HasForeignKey("Acadify.Models.Db.MatchingStatus", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MatchStatus_Student");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Acadify.Models.Db.Meeting", b =>
                {
                    b.HasOne("Acadify.Models.Db.Advisor", "Advisor")
                        .WithMany("Meetings")
                        .HasForeignKey("AdvisorId")
                        .IsRequired()
                        .HasConstraintName("FK_Meeting_Advisor");

                    b.HasOne("Acadify.Models.Db.Student", "Student")
                        .WithMany("Meetings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Meeting_Student");

                    b.Navigation("Advisor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Acadify.Models.Db.MeetingForm", b =>
                {
                    b.HasOne("Acadify.Models.Db.Form", "Form")
                        .WithOne("MeetingForm")
                        .HasForeignKey("Acadify.Models.Db.MeetingForm", "FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MeetingForm_Forms");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Acadify.Models.Db.NextSemesterCourseSelectionForm", b =>
                {
                    b.HasOne("Acadify.Models.Db.Form", "Form")
                        .WithOne("NextSemesterCourseSelectionForm")
                        .HasForeignKey("Acadify.Models.Db.NextSemesterCourseSelectionForm", "FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NSCSF_Forms");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Acadify.Models.Db.Notification", b =>
                {
                    b.HasOne("Acadify.Models.Db.Advisor", "Advisor")
                        .WithMany("Notifications")
                        .HasForeignKey("AdvisorId")
                        .HasConstraintName("FK_Notif_Advisor");

                    b.HasOne("Acadify.Models.Db.Student", "Student")
                        .WithMany("Notifications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Notif_Student");

                    b.Navigation("Advisor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Acadify.Models.Db.Student", b =>
                {
                    b.HasOne("Acadify.Models.Db.Advisor", "Advisor")
                        .WithMany("Students")
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Student_Advisor");

                    b.Navigation("Advisor");
                });

            modelBuilder.Entity("Acadify.Models.Db.StudyPlanMatchingForm", b =>
                {
                    b.HasOne("Acadify.Models.Db.Form", "Form")
                        .WithOne("StudyPlanMatchingForm")
                        .HasForeignKey("Acadify.Models.Db.StudyPlanMatchingForm", "FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SPMF_Forms");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Acadify.Models.Db.Transcript", b =>
                {
                    b.HasOne("Acadify.Models.Db.Student", "Student")
                        .WithOne("Transcript")
                        .HasForeignKey("Acadify.Models.Db.Transcript", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Transcript_Student");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudyPlanCourse", b =>
                {
                    b.HasOne("Acadify.Models.Db.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_SPC_Course");

                    b.HasOne("Acadify.Models.Db.StudyPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SPC_StudyPlan");
                });

            modelBuilder.Entity("TranscriptCourse", b =>
                {
                    b.HasOne("Acadify.Models.Db.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_TC_Course");

                    b.HasOne("Acadify.Models.Db.Transcript", null)
                        .WithMany()
                        .HasForeignKey("TranscriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TC_Transcript");
                });

            modelBuilder.Entity("Acadify.Models.Db.Advisor", b =>
                {
                    b.Navigation("Forms");

                    b.Navigation("Meetings");

                    b.Navigation("Notifications");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Acadify.Models.Db.Community", b =>
                {
                    b.Navigation("CommunityMessages");
                });

            modelBuilder.Entity("Acadify.Models.Db.Form", b =>
                {
                    b.Navigation("AcademicAdvisingConfirmationForm");

                    b.Navigation("CourseChoiceMonitoringForm");

                    b.Navigation("GraduationProjectEligibilityForm");

                    b.Navigation("MeetingForm");

                    b.Navigation("NextSemesterCourseSelectionForm");

                    b.Navigation("StudyPlanMatchingForm");
                });

            modelBuilder.Entity("Acadify.Models.Db.Student", b =>
                {
                    b.Navigation("Forms");

                    b.Navigation("GraduationStatus");

                    b.Navigation("MatchingStatus");

                    b.Navigation("Meetings");

                    b.Navigation("Notifications");

                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("Acadify.Models.Db.User", b =>
                {
                    b.Navigation("Advisor");
                });
#pragma warning restore 612, 618
        }
    }
}
